"""file field in Recipe

Revision ID: 01bd7b2a5e63
Revises: 3a22e89ac640
Create Date: 2025-09-09 20:28:23.422683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bd7b2a5e63'
down_revision = '3a22e89ac640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
