"""update tables

Revision ID: 5a9ec01f2ba7
Revises: 58da0ddb0b8b
Create Date: 2025-08-22 01:35:41.552871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9ec01f2ba7'
down_revision = '58da0ddb0b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_category_title'))
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)
        batch_op.drop_column('title')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_title'))
        batch_op.drop_column('title')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_index(batch_op.f('ix_category_title'), ['title'], unique=1)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
