"""add links field in recipe table

Revision ID: 91b053cd9e50
Revises: 5a9ec01f2ba7
Create Date: 2025-08-25 00:52:08.436636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b053cd9e50'
down_revision = '5a9ec01f2ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('links')

    # ### end Alembic commands ###
